// <auto-generated />
namespace LTQLBT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createtableemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtableemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202109140646208_create-table-employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
